name: Playwright test reusable workflow

on:
  workflow_call:
    inputs:
      shard:
        description: 'Shard number'
        required: true
        type: string
      db:
        required: true
        type: string

jobs:
  playwright:
    runs-on: ubuntu-20.04
    steps:
      # Reference: https://github.com/pierotofy/set-swap-space/blob/master/action.yml
      - name: Set 5gb swap
        shell: bash
        # Delete the swap file, allocate a new one, and activate it
        run: |
            export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
            sudo swapoff $SWAP_FILE
            sudo rm $SWAP_FILE
            sudo fallocate -l 5G $SWAP_FILE
            sudo chmod 600 $SWAP_FILE
            sudo mkswap $SWAP_FILE
            sudo swapon $SWAP_FILE
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules

        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install dependencies nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm install
      - name: build nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm run build
      - name: setup mysql
        if: ${{ inputs.db == 'mysql' }}
        working-directory: ./
        run: docker-compose -f ./packages/nc-gui/tests/playwright/scripts/docker-compose-mysql-playwright.yml up -d &
      - name: setup pg
        if: ${{ inputs.db == 'pg' }}
        working-directory: ./
        run: docker-compose -f ./packages/nc-gui/tests/playwright/scripts/docker-compose-playwright-pg.yml up -d &
      - name: setup pg for quick tests
        if: ${{ inputs.db == 'sqlite' && inputs.shard == '1' }}
        working-directory: ./
        run: docker-compose -f ./packages/nc-gui/tests/playwright/scripts/docker-compose-pg-pw-quick.yml up -d &
      - name: run frontend
        working-directory: ./packages/nc-gui
        run: npm run ci:run
      - name: Run backend
        working-directory: ./packages/nocodb
        run: npm run ci:run &
      - name: Cache playwright npm modules
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            **/playwright/node_modules
          key: cache-nc-playwright-${{ hashFiles('**/playwright/package-lock.json') }}
      - name: Install dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./packages/nc-gui/tests/playwright
        run: npm install
      - name: Install Playwright Browsers
        working-directory: ./packages/nc-gui/tests/playwright
        run: npx playwright install chromium --with-deps
      - name: Wait for backend
        run: |
          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
            printf '.'
            sleep 2
          done

      - name: Run Playwright tests
        working-directory: ./packages/nc-gui/tests/playwright
        run: E2E_DB_TYPE=${{ inputs.db }} npm run ci:test:shard:${{ inputs.shard }}

      # Quick tests (pg on sqlite shard 0 and sqlite on sqlite shard 1)
      - name: Run quick server and tests (pg)
        if: ${{ inputs.db == 'sqlite' && inputs.shard == '1' }}
        working-directory: ./packages/nocodb
        run: |
          kill -9 $(lsof -t -i:8080)
          npm run watch:run:playwright:pg:cyquick &
          cd ../nc-gui/tests/playwright
          npm run test:quick
      - name: Run quick server and tests (sqlite)
        if: ${{ inputs.db == 'sqlite' && inputs.shard == '2' }}
        working-directory: ./packages/nocodb
        run: | 
          kill -9 $(lsof -t -i:8080)
          npm run watch:run:playwright:quick &
          cd ../nc-gui/tests/playwright
          npm run test:quick

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ inputs.db }}-${{ inputs.shard }}
          path: ./packages/nc-gui/tests/playwright/playwright-report/
          retention-days: 2
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backend-logs-${{ inputs.db }}-${{ inputs.shard }}
          path: ./packages/nocodb/mysql_test_backend.log
          retention-days: 2